# Generated by Django 5.1.5 on 2025-01-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webvideos', '0007_alter_addedinfo_type_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='vides',
            field=models.ManyToManyField(related_name='actors', to='webvideos.video'),
        ),
        migrations.AlterField(
            model_name='addedinfo',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Drama'), (3, 'Sci-Fi'), (2, 'Comedy'), (0, 'Other'), (1, 'Horror')], default=0),
        ),
    ]
