# Generated by Django 5.1.5 on 2025-01-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webvideos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='year',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
