# Generated by Django 5.1.5 on 2025-01-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webvideos', '0002_video_year_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='poster',
            field=models.ImageField(null=True, upload_to='posters'),
        ),
        migrations.AddField(
            model_name='video',
            name='premiere',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
