# Generated by Django 5.1.5 on 2025-01-29 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webvideos', '0005_addedinfo_video_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addedinfo',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Comedy'), (1, 'Horror'), (0, 'Other'), (4, 'Drama'), (3, 'Sci-Fi')], default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, default='')),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webvideos.video')),
            ],
        ),
    ]
