# Generated by Django 5.1.5 on 2025-01-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webvideos', '0006_alter_addedinfo_type_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addedinfo',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-Fi'), (0, 'Other'), (1, 'Horror'), (2, 'Comedy'), (4, 'Drama')], default=0),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('vides', models.ManyToManyField(to='webvideos.video')),
            ],
        ),
    ]
